---

- name: Include secrets
  include_vars:
    file: defaults/secret.yml

- name: Put secret file
  template:
    src: templates/template.j2
    dest: "{{ secrets_destination }}"
    owner: root
    group: root
    mode: 0400

- name: Output secret
  shell: "cat {{ secrets_destination }}"
  when: secrets_show is defined
  tags: debug
